apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocean-user-behavior-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocean-user-behavior-service
  template:
    metadata:
      labels:
        app: ocean-user-behavior-service
    spec:
      containers:
        - name: ocean-user-behavior-service
          image: boyuzhu4216/ocean-user-behavior-service:v1.0
          ports:
            - containerPort: 8088
          resources:
            requests:
              cpu: "150m"   
              memory: "256Mi" 
            limits:
              cpu: "600m"  
              memory: "512Mi" 


---

apiVersion: v1
kind: Service
metadata:
  name: ocean-user-behavior-service
spec:
  selector:
    app: ocean-user-behavior-service
  ports:
    - port: 8088
      targetPort: 8088
  type: ClusterIP
