apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocean-collection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocean-collection-service
  template:
    metadata:
      labels:
        app: ocean-collection-service
    spec:
      containers:
        - name: ocean-collection-service
          image: boyuzhu4216/ocean-collection-service:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "150m"   
              memory: "256Mi" 
            limits:
              cpu: "600m"  
              memory: "512Mi" 



---

apiVersion: v1
kind: Service
metadata:
  name: ocean-collection-service
spec:
  selector:
    app: ocean-collection-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
