server:
  port: 8080

spring:
  application:
    name: ocean-gateway
  cloud:
    nacos:
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yaml
        group: DEFAULT_GROUP
      discovery:
        server-addr: ocean-nacos:8848
    gateway:
      routes:
        - id: login
          uri: lb://ocean-user-service
          predicates:
            - Path=/userAuth/login
          filters:
            - UserAuth
        - id: user # 路由规则id，自定义，唯一
          uri: lb://ocean-user-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/userWalletService/**,/userInfoService/**,/userFunctionService/**, # 这里是以请求路径作为判断规则
        - id: docs
          uri: lb://ocean-docs-service
          predicates:
            - Path=/docClassificationService/**, /docFunctionService/**, /docInfoService/**, /docSearchService/**
        - id: comment
          uri: lb://ocean-comment-service
          predicates:
            - Path=/comment/**
        - id: collection
          uri: lb://ocean-collection-service
          predicates:
            - Path=/collectionService/**
        - id: notify
          uri: lb://ocean-notify-service
          predicates:
            - Path=/notify/**
        - id: note
          uri: lb://ocean-note-service
          predicates:
              - Path=/noteService/**
auth:
  login:
    token:
      secretkey: '!QXw1O8WM7eKH4FEP*(*J%xT$%ugs%kz'
